Repository openshift/dpu-operator, pull requests merged in 2024-06, with the labels that each got.

#77 Cleanup Device Plugin Code
  daemon/device-plugin/deviceplugin.go
Labels: approved, lgtm

#79 Fix Device Plugin and Daemon bugs
  daemon/device-plugin/deviceplugin.go
  internal/controller/bindata/daemon/02.daemon_role.yaml
Labels: approved, lgtm

#80 Fix DPU CNI binary copy regression
  daemon/main.go
Labels: approved, lgtm

#81 Fix bug in Host Daemon where the daemon would exit immediately
  daemon/dpudaemon.go
  daemon/hostdaemon.go
Labels: approved, lgtm

#83 OCPBUGS-35339: Fix labels
  bundle/manifests/dpu-operator.clusterserviceversion.yaml
  config/manifests/bases/dpu-operator.clusterserviceversion.yaml
  manifests/stable/dpu-operator.clusterserviceversion.yaml
Labels: jira/valid-bug, approved, lgtm, jira/valid-reference

#78 Rework Device Plugin To Handle Multiple Device Types
  daemon/device-plugin/deviceplugin.go
  daemon/device-plugin/types.go
  daemon/main.go
  daemon/nf-device-handler/nfdevicehandler.go
Labels: approved, lgtm

#84 OCPBUGS-35340: Fix labels
  Makefile
  bundle.Dockerfile
  bundle/manifests/config.openshift.io_dpuoperatorconfigs.yaml
  bundle/manifests/dpu-operator.clusterserviceversion.yaml
  bundle/metadata/annotations.yaml
  config/crd/bases/config.openshift.io_dpuoperatorconfigs.yaml
  config/manifests/bases/dpu-operator.clusterserviceversion.yaml
  manifests/stable/config.openshift.io_dpuoperatorconfigs.yaml
  manifests/stable/dpu-operator.clusterserviceversion.yaml
Labels: jira/valid-bug, approved, lgtm, backport-risk-assessed, cherry-pick-approved, jira/valid-reference

#86 Bump go version to 1.22.1
  api/go.mod
  bundle/manifests/dpu-operator.clusterserviceversion.yaml
  dpu-api/go.mod
  go.mod
  manifests/stable/dpu-operator.clusterserviceversion.yaml
  vendor/modules.txt
Labels: approved, lgtm

#87 Move daemon into internal directory and to cmd/daemon/daemon.go
  Dockerfile.daemon.rhel
  cmd/daemon/daemon.go
  internal/daemon/device-handler/nf-device-handler/nfdevicehandler.go
  internal/daemon/device-handler/sriov-device-handler/sriovdevicehandler.go
  internal/daemon/device-handler/utils.go
  internal/daemon/device-plugin/deviceplugin.go
  internal/daemon/device-plugin/types.go
  internal/daemon/dpudaemon.go
  internal/daemon/hostdaemon.go
  internal/daemon/hostdaemon_test.go
  internal/daemon/plugin/vendorplugin.go
  internal/daemon/sfc-reconciler/sfc.go
  internal/daemon/suite_test.go
Labels: approved, lgtm

#90 Improve host daemon testing
  internal/daemon/hostdaemon.go
  internal/daemon/hostdaemon_test.go
Labels: approved, lgtm

#91 Cleanup testing
  internal/controller/dpuoperatorconfig_controller_test.go
  internal/controller/suite_test.go
  internal/testutils/test_cluster.go
Labels: approved, lgtm

#93 Add generate-check make target
  Makefile
Labels: approved, lgtm

#94 Return from error to restart reconcile
  internal/controller/dpuoperatorconfig_controller.go
Labels: approved, lgtm

#95 Switch to ginkgo for testing
  Makefile
Labels: approved, lgtm

#97 Fix side effect from test
  dpu-cni/pkgs/cniserver/cniserver_test.go
  internal/daemon/hostdaemon_test.go
Labels: approved, lgtm

#92 Fix race and introduce dpu daemon test
  internal/daemon/dpudaemon.go
  internal/daemon/dpudaemon_test.go
  internal/daemon/hostdaemon_test.go
Labels: approved, lgtm

#98 Add err code for "make generate-check"
  Makefile
Labels: approved, lgtm

#100 Update "make generate"
  api/v1/zz_generated.deepcopy.go
Labels: approved, lgtm

#99 Introduce infrastructure needed to test against kubelet in kind
  dpu-cni/pkgs/cniserver/cniserver.go
  dpu-cni/pkgs/cniserver/cniserver_test.go
  internal/daemon/dpudaemon.go
  internal/daemon/dpudaemon_test.go
  internal/daemon/hostdaemon.go
  internal/daemon/hostdaemon_test.go
  internal/testutils/test_cluster.go
  internal/utils/path_manager.go
Labels: approved, lgtm

#102 Add prow-ci- manifest-check & bundle-check rule for PROW CI
  Makefile
Labels: approved, lgtm

#103 Make DPU operator config cluster scope
  api/v1/dpuoperatorconfig_types.go
  bundle/manifests/config.openshift.io_dpuoperatorconfigs.yaml
  bundle/manifests/dpu-operator.clusterserviceversion.yaml
  config/crd/bases/config.openshift.io_dpuoperatorconfigs.yaml
  config/default/kustomization.yaml
  config/manifests/bases/dpu-operator.clusterserviceversion.yaml
  examples/dpu.yaml
  examples/host.yaml
  internal/controller/dpuoperatorconfig_controller.go
  internal/daemon/dpudaemon.go
  internal/daemon/hostdaemon.go
  internal/daemon/sfc-reconciler/sfc.go
  manifests/stable/config.openshift.io_dpuoperatorconfigs.yaml
  manifests/stable/dpu-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#104 Add detection of {micro,open}shift to handle CNI binary
  cmd/daemon/daemon.go
  config/rbac/role.yaml
  internal/controller/bindata/daemon/02.daemon_role.yaml
  internal/controller/bindata/daemon/04.daemon_cluster_role.yaml
  internal/controller/bindata/daemon/05.daemon_cluster_role_binding.yaml
  internal/controller/bindata/daemon/06.daemon_role_kube_public.yaml
  internal/controller/bindata/daemon/07.daemon_role_binding_kube_public.yaml
  internal/controller/bindata/daemon/99.daemonset.yaml
  internal/controller/dpuoperatorconfig_controller.go
  internal/daemon/dpudaemon.go
  internal/daemon/dpudaemon_test.go
  internal/utils/cluster_environment.go
  internal/utils/path_manager.go
Labels: approved, lgtm

#107 Autodetect mode on daemon
  cmd/daemon/daemon.go
  internal/controller/dpuoperatorconfig_controller.go
  internal/controller/dpuoperatorconfig_controller_test.go
  internal/platform/platform.go
Labels: approved, lgtm
