Repository openshift/dpu-operator, pull requests merged in 2024-10, with the labels that each got.

#154 OCPBUGS-39605,OCPBUGS-39499,OCPBUGS-39446: Bump to 4.18
  .ci-operator.yaml
  Dockerfile.CNI.rhel
  Dockerfile.daemon.rhel
  Dockerfile.rhel
Labels: jira/valid-bug, approved, lgtm, jira/valid-reference

#162 Add GetDevice() to Marvell VSP
  Dockerfile.mrvlVSP.rhel
  internal/daemon/vendor-specific-plugins/marvell/main.go
Labels: approved, lgtm, ok-to-test

#174 Remove hardcoded PCI address
  internal/controller/bindata/daemon/02.daemon_role.yaml
  internal/daemon/device-handler/sriov-device-handler/sriovdevicehandler.go
Labels: approved, lgtm

#178 E2e cleanup
  Makefile
  hack/deploy_traffic_flow_tests.sh
  hack/ipu_deploy.sh
  hack/ipu_host_deploy.sh
  hack/prepare.sh
Labels: approved, lgtm

#175 fix deprecated field and rename and move e2e files
  hack/cluster-configs/config-dpu-host.yaml
  hack/cluster-configs/config-dpu.yaml
  hack/cluster-configs/ocp-tft-config.yaml
  hack/deploy_traffic_flow_tests.sh
  hack/ipu_deploy.sh
  hack/ipu_host_deploy.sh
Labels: approved, lgtm

#179 Fix failing daemon deployment
  bundle/manifests/dpu-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  internal/controller/dpuoperatorconfig_controller.go
  manifests/stable/dpu-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#186 Add make_fast_e2e_test target to dpu operator
  Makefile
  hack/deploy_fast.sh
  hack/ipu_deploy_post.sh
  hack/ipu_host_deploy_post.sh
Labels: approved, lgtm

#184 Add makefile target to check vendor
  Makefile
Labels: approved, lgtm

#183 Fix go mod vendor and protoc versioning
  api/v1/servicefunctionchain_types.go
  api/v1/zz_generated.deepcopy.go
  dpu-api/gen/api.pb.go
  dpu-api/gen/api_grpc.pb.go
  vendor/github.com/openshift/dpu-operator/api/v1/servicefunctionchain_types.go
  vendor/github.com/openshift/dpu-operator/api/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/dpu-operator/dpu-api/gen/api.pb.go
  vendor/github.com/openshift/dpu-operator/dpu-api/gen/api_grpc.pb.go
  vendor/k8s.io/client-go/util/testing/fake_handler.go
  vendor/k8s.io/client-go/util/testing/fake_openapi_handler.go
  vendor/k8s.io/client-go/util/testing/remove_file.go
  vendor/k8s.io/client-go/util/testing/tmpdir.go
Labels: approved, lgtm

#190 Use mktemp when running vendor check
  Makefile
Labels: approved, lgtm

#185 Run tests 5 times
  Makefile
Labels: approved, lgtm

#200 Proper device handler
  cmd/daemon/daemon.go
  dpu-cni/pkgs/sriovutils/sriovutils.go
  go.mod
  hack/cluster-configs/config-dpu-host.yaml
  hack/cluster-configs/config-dpu.yaml
  internal/daemon/device-handler/dpu-device-handler/dpudevicehandler.go
  internal/daemon/device-handler/nf-device-handler/nfdevicehandler.go
  internal/daemon/device-handler/sriov-device-handler/sriovdevicehandler.go
  internal/daemon/dpudaemon_test.go
  vendor/modules.txt
Labels: approved, lgtm

#198 separate prepare script
  Makefile
  hack/prepare-submodules.sh
  hack/prepare-venv.sh
Labels: approved, lgtm
