Repository openshift/dpu-operator, pull requests merged in 2024-08, with the labels that each got.

#126 NO-JIRA: fix image references in 4.18
  manifests/stable/dpu-operator.clusterserviceversion.yaml
  manifests/stable/image-references
Labels: approved, lgtm, backport-risk-assessed, jira/valid-reference

#127 OCPBUGS-38428: fix image references in 4.17
  manifests/stable/dpu-operator.clusterserviceversion.yaml
  manifests/stable/image-references
Labels: jira/valid-bug, approved, lgtm, backport-risk-assessed, cherry-pick-approved, jira/valid-reference

#129 OCPBUGS-38580: Bump 4.17 manifests
  Makefile
  bundle/manifests/dpu-operator.clusterserviceversion.yaml
  manifests/dpu-operator.package.yaml
  manifests/stable/dpu-operator.clusterserviceversion.yaml
Labels: jira/valid-bug, approved, lgtm, backport-risk-assessed, cherry-pick-approved, jira/valid-reference

#130 OCPBUGS-38581: Bump 4.18 manifests
  Makefile
  bundle/manifests/dpu-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  manifests/dpu-operator.package.yaml
  manifests/stable/dpu-operator.clusterserviceversion.yaml
Labels: jira/valid-bug, approved, lgtm, backport-risk-assessed, jira/valid-reference

#132 OCPBUGS-38580: [4.17] Bump manifests to 4.17
  bundle/manifests/dpu-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  manifests/stable/dpu-operator.clusterserviceversion.yaml
Labels: jira/valid-bug, approved, lgtm, backport-risk-assessed, cherry-pick-approved, jira/valid-reference

#124 proto file change for SetNumVfs
  dpu-api/api.proto
  dpu-api/gen/api.pb.go
  dpu-api/gen/api_grpc.pb.go
Labels: approved, lgtm, ok-to-test

#139 Use relative path
  cluster_configs/config-dpu-host.yaml
  cluster_configs/config-dpu.yaml
Labels: approved, lgtm

#140 Cleanup cluster-deployment automation code
  hack/ipu_deploy.sh
  hack/ipu_host_deploy.sh
  hack/prepare.sh
Labels: approved, lgtm
