Repository openshift/dpu-operator, pull requests merged in 2025-05, with the labels that each got.

#371 IIC-448: Remove workaround for call to GetDevices
  internal/daemon/device-handler/dpu-device-handler/dpudevicehandler.go
Labels: approved, lgtm

#379 Add owner
  OWNERS
Labels: approved, lgtm, ok-to-test

#381 Add explanation of using taskfile
  README.md
Labels: approved, lgtm

#349 Marvell: Add Support for NetworkFunction in VSP
  internal/daemon/vendor-specific-plugins/marvell/debug-dp/debugdp.go
  internal/daemon/vendor-specific-plugins/marvell/main.go
  internal/daemon/vendor-specific-plugins/marvell/mrvl-utils/mrvlutils.go
  internal/daemon/vendor-specific-plugins/marvell/ovs-dp/ovsdp.go
Labels: approved, lgtm, ok-to-test

#383 [th/tft-venv-update] hack: upgrade pip modules for tft-venv
  hack/prepare-venv.sh
Labels: approved, lgtm

#386 Correcting typo and adding inc dockerfiles to gitignore
  .gitignore
  taskfile.yaml
Labels: needs-ok-to-test, approved, lgtm

#385 Fix image url and cleanup of makefile
  .dockerignore
  Makefile
  config/dev/local-images-template.yaml
  taskfile.yaml
  taskfiles/clusters.yaml
Labels: approved, lgtm

#391 Fix cleaning image layer
  taskfiles/images.yaml
Labels: approved, lgtm

#396 OWNERS: Add samd2021 as maintainer
  OWNERS
Labels: needs-ok-to-test, approved, lgtm

#393 add status to clean image target
  taskfiles/images.yaml
Labels: approved, lgtm
