Repository openshift/dpu-operator, pull requests merged in 2025-07, with the labels that each got.

#456 Dectection loop and handle racy starts
  cmd/daemon/daemon.go
  internal/daemon/daemon.go
  internal/daemon/daemon_test.go
  internal/daemon/plugin/vendorplugin.go
Labels: approved, lgtm

#458 Migrate more targets into taskfile
  Makefile
  taskfile.yaml
  taskfiles/images.yaml
  taskfiles/operator-sdk.yaml
  taskfiles/proto.yaml
Labels: approved, lgtm

#461 taskfiles: drop workaround for deploying marvell
  taskfiles/clusters.yaml
Labels: approved, lgtm

#464 More logging and cache workload pod images
  e2e_test/e2e_test.go
  internal/testutils/testcluster.go
Labels: approved, lgtm

#466 Add a new pcie field to the Init request from Daemon to VSP
  dpu-api/api.proto
  dpu-api/gen/api.pb.go
  dpu-api/gen/api_grpc.pb.go
  vendor/github.com/openshift/dpu-operator/dpu-api/gen/api.pb.go
  vendor/github.com/openshift/dpu-operator/dpu-api/gen/api_grpc.pb.go
Labels: approved, lgtm

#468 OCPBUGS-58423: Fix Brew build issues for dpu-intel-ipu-vsp
  openshift/install-dpu.sh
  openshift/requirements-build.txt
Labels: jira/valid-bug, approved, lgtm, jira/valid-reference

#479 [th/fix-prepare-venv] prepare-venv: fix checking for valid ktoolbox package in venv
  hack/prepare-venv.sh
Labels: approved, lgtm

#475 Making the SFC container to be in privileged mode
  examples/my-pod.yaml
  internal/daemon/sfc-reconciler/sfc.go
Labels: approved, lgtm, ok-to-test

#484 IPU plugin version update
  go.mod
  go.sum
  vendor/github.com/intel/ipu-opi-plugins/ipu-plugin/pkg/ipuplugin/lifecycleservice.go
  vendor/github.com/intel/ipu-opi-plugins/ipu-plugin/pkg/p4rtclient/p4rtclient.go
  vendor/github.com/intel/ipu-opi-plugins/ipu-plugin/pkg/utils/utils.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test

#485 Add OvS Support for the PTL
  internal/daemon/vendor-specific-plugins/common/vspnetutils.go
  internal/daemon/vendor-specific-plugins/intel-netsec/main.go
Labels: approved, lgtm

#488 IIC-711 Replace VSP P4 dockerfile with the P4 dockerfile
  Dockerfile.IntelP4.rhel
  Dockerfile.IntelVSPP4.rhel
  taskfiles/images.yaml
Labels: approved, lgtm, ok-to-test
